joint_position_controller:
    type: serl_franka_controllers/JointPositionController
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

cartesian_impedance_controller:
    type: serl_franka_controllers/CartesianImpedanceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

joint_persistent_controller:
  type: serl_franka_controllers/JointPersistentController
  
  # Timing parameters
  interpolation_time: 0.02      # Minimum interpolation time (50ms for high dynamics)
  
  # Dynamic limits
  max_velocity: 2.5             # Maximum joint velocity (rad/s)
  max_acceleration: 15.0        # Maximum joint acceleration (rad/s^2)
  
  # Control parameters
  use_smooth_interpolation: true    # Use S-curve interpolation
  position_tolerance: 0.002         # Position tolerance (rad)
  velocity_filter_gain: 0.3         # Velocity filter gain (0-1)
  
  # Joint names (automatically set in code)
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7


joint_impedance_controller:
    type: serl_franka_controllers/JointImpedanceExampleController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    k_gains:
        - 600.0
        - 600.0
        - 600.0
        - 600.0
        - 250.0
        - 150.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0
    radius: 0.1
    acceleration_time: 1.0
    vel_max: 0.3
    publish_rate: 50.0
    coriolis_factor: 1.0